# Generated by Django 4.1.5 on 2024-02-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avlbl",
        ),
    ]
